security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
          pattern: (_(proifler|wdt))/
          security: false
        main:
            pattern: .*
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: true
                default_target_path: eplugg_front_homepage
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            remember_me:
              key: %secret%
              lifetime: 300000000
              path: /
              domain: ~
            logout:
                path:   fos_user_security_logout
                target: eplugg_front_homepage			
            anonymous:    true
