services:
#    eplugg_user.example:
#        class: Eplugg\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     app_user.registration.form.type:
        class: Eplugg\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
        - { name: form.type, alias: app_user_registration }
     app_user_change_password.form.type:
        class: Eplugg\UserBundle\Form\Type\ChangePasswordFormType
        arguments: [%fos_user.model.user.class%]
        tags:
        - { name: form.type, alias: app_user_change_password }
