<?php

namespace Proxies\__CG__\Eplugg\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Eplugg\UserBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'firstName', 'lastName', 'gender', 'job', 'sociaux', 'mobile', 'direct_phone', 'avatar', 'company_name', 'company_activity', 'company_country', 'company_city', 'company_address', 'company_tel', 'company_fax', 'company_website', 'company_logo', 'birthday', 'birthmonth', 'birthyear', 'more_emails', 'profileCompleted', 'cv', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'experiences', 'companyAvatar', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'users_one', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'users_two', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'messagesSource', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'messagesDestination', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'users_action', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'users_from_suggestion', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'users_to_suggestion', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'users_suggested', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'user_fromIgnored_id', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'user_ignored_id', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'user_events', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'activities', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'userLog', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'userLogTarget', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'timer', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'status', 'latitude', 'longitude', 'username', 'usernameCanonical', 'email', 'emailCanonical', 'enabled', 'salt', 'password', 'plainPassword', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'locked', 'expired', 'expiresAt', 'roles', 'credentialsExpired', 'credentialsExpireAt');
        }

        return array('__isInitialized__', 'id', 'firstName', 'lastName', 'gender', 'job', 'sociaux', 'mobile', 'direct_phone', 'avatar', 'company_name', 'company_activity', 'company_country', 'company_city', 'company_address', 'company_tel', 'company_fax', 'company_website', 'company_logo', 'birthday', 'birthmonth', 'birthyear', 'more_emails', 'profileCompleted', 'cv', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'experiences', 'companyAvatar', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'users_one', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'users_two', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'messagesSource', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'messagesDestination', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'users_action', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'users_from_suggestion', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'users_to_suggestion', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'users_suggested', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'user_fromIgnored_id', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'user_ignored_id', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'user_events', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'activities', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'userLog', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'userLogTarget', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'timer', '' . "\0" . 'Eplugg\\UserBundle\\Entity\\User' . "\0" . 'status', 'latitude', 'longitude', 'username', 'usernameCanonical', 'email', 'emailCanonical', 'enabled', 'salt', 'password', 'plainPassword', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'locked', 'expired', 'expiresAt', 'roles', 'credentialsExpired', 'credentialsExpireAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($lastName));

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setJob($job)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJob', array($job));

        return parent::setJob($job);
    }

    /**
     * {@inheritDoc}
     */
    public function getJob()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJob', array());

        return parent::getJob();
    }

    /**
     * {@inheritDoc}
     */
    public function setSociaux($sociaux)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSociaux', array($sociaux));

        return parent::setSociaux($sociaux);
    }

    /**
     * {@inheritDoc}
     */
    public function getSociaux()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSociaux', array());

        return parent::getSociaux();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobile($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobile', array($mobile));

        return parent::setMobile($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobile', array());

        return parent::getMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirectPhone($directPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirectPhone', array($directPhone));

        return parent::setDirectPhone($directPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirectPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirectPhone', array());

        return parent::getDirectPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPicture($userPicture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPicture', array($userPicture));

        return parent::setUserPicture($userPicture);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPicture', array());

        return parent::getUserPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyName($companyName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyName', array($companyName));

        return parent::setCompanyName($companyName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyName', array());

        return parent::getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyActivity($companyActivity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyActivity', array($companyActivity));

        return parent::setCompanyActivity($companyActivity);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyActivity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyActivity', array());

        return parent::getCompanyActivity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyCountry($companyCountry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyCountry', array($companyCountry));

        return parent::setCompanyCountry($companyCountry);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyCountry', array());

        return parent::getCompanyCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyCity($companyCity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyCity', array($companyCity));

        return parent::setCompanyCity($companyCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyCity', array());

        return parent::getCompanyCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyAddress($companyAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyAddress', array($companyAddress));

        return parent::setCompanyAddress($companyAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyAddress', array());

        return parent::getCompanyAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyTel($companyTel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyTel', array($companyTel));

        return parent::setCompanyTel($companyTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyTel', array());

        return parent::getCompanyTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyFax($companyFax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyFax', array($companyFax));

        return parent::setCompanyFax($companyFax);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyFax', array());

        return parent::getCompanyFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyWebsite($companyWebsite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyWebsite', array($companyWebsite));

        return parent::setCompanyWebsite($companyWebsite);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyWebsite', array());

        return parent::getCompanyWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyLogo($companyLogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyLogo', array($companyLogo));

        return parent::setCompanyLogo($companyLogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyLogo', array());

        return parent::getCompanyLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', array($birthday));

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', array());

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthmonth($birthmonth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthmonth', array($birthmonth));

        return parent::setBirthmonth($birthmonth);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthmonth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthmonth', array());

        return parent::getBirthmonth();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthyear($birthyear)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthyear', array($birthyear));

        return parent::setBirthyear($birthyear);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthyear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthyear', array());

        return parent::getBirthyear();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileCompleted($profileCompleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileCompleted', array($profileCompleted));

        return parent::setProfileCompleted($profileCompleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileCompleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileCompleted', array());

        return parent::getProfileCompleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setMoreEmails($moreEmails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMoreEmails', array($moreEmails));

        return parent::setMoreEmails($moreEmails);
    }

    /**
     * {@inheritDoc}
     */
    public function getMoreEmails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMoreEmails', array());

        return parent::getMoreEmails();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadRootDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadRootDir', array());

        return parent::getUploadRootDir();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadDir', array());

        return parent::getUploadDir();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setCv(\Eplugg\UserBundle\Entity\File $cv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCv', array($cv));

        return parent::setCv($cv);
    }

    /**
     * {@inheritDoc}
     */
    public function getCv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCv', array());

        return parent::getCv();
    }

    /**
     * {@inheritDoc}
     */
    public function addExperience(\Eplugg\UserBundle\Entity\Experience $experiences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExperience', array($experiences));

        return parent::addExperience($experiences);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExperience(\Eplugg\UserBundle\Entity\Experience $experiences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExperience', array($experiences));

        return parent::removeExperience($experiences);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperiences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperiences', array());

        return parent::getExperiences();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar(\Eplugg\UserBundle\Entity\Image $avatar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', array($avatar));

        return parent::setAvatar($avatar);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', array());

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyAvatar(\Eplugg\UserBundle\Entity\Image $companyAvatar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyAvatar', array($companyAvatar));

        return parent::setCompanyAvatar($companyAvatar);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyAvatar', array());

        return parent::getCompanyAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersOne(\Eplugg\BackBundle\Entity\Relationship $usersOne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersOne', array($usersOne));

        return parent::addUsersOne($usersOne);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersOne(\Eplugg\BackBundle\Entity\Relationship $usersOne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersOne', array($usersOne));

        return parent::removeUsersOne($usersOne);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersOne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersOne', array());

        return parent::getUsersOne();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersTwo(\Eplugg\BackBundle\Entity\Relationship $usersTwo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersTwo', array($usersTwo));

        return parent::addUsersTwo($usersTwo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersTwo(\Eplugg\BackBundle\Entity\Relationship $usersTwo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersTwo', array($usersTwo));

        return parent::removeUsersTwo($usersTwo);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersTwo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersTwo', array());

        return parent::getUsersTwo();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersAction(\Eplugg\BackBundle\Entity\RelationshipAction $usersAction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersAction', array($usersAction));

        return parent::addUsersAction($usersAction);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersAction(\Eplugg\BackBundle\Entity\RelationshipAction $usersAction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersAction', array($usersAction));

        return parent::removeUsersAction($usersAction);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersAction', array());

        return parent::getUsersAction();
    }

    /**
     * {@inheritDoc}
     */
    public function addMessagesSource(\Eplugg\BackBundle\Entity\Relationship $messagesSource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessagesSource', array($messagesSource));

        return parent::addMessagesSource($messagesSource);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMessagesSource(\Eplugg\BackBundle\Entity\Relationship $messagesSource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMessagesSource', array($messagesSource));

        return parent::removeMessagesSource($messagesSource);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessagesSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessagesSource', array());

        return parent::getMessagesSource();
    }

    /**
     * {@inheritDoc}
     */
    public function addMessagesDestination(\Eplugg\BackBundle\Entity\Message $messagesDestination)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMessagesDestination', array($messagesDestination));

        return parent::addMessagesDestination($messagesDestination);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMessagesDestination(\Eplugg\BackBundle\Entity\Message $messagesDestination)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMessagesDestination', array($messagesDestination));

        return parent::removeMessagesDestination($messagesDestination);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessagesDestination()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessagesDestination', array());

        return parent::getMessagesDestination();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersFromSuggestion(\Eplugg\BackBundle\Entity\Suggestion $usersFromSuggestion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersFromSuggestion', array($usersFromSuggestion));

        return parent::addUsersFromSuggestion($usersFromSuggestion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersFromSuggestion(\Eplugg\BackBundle\Entity\Suggestion $usersFromSuggestion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersFromSuggestion', array($usersFromSuggestion));

        return parent::removeUsersFromSuggestion($usersFromSuggestion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersFromSuggestion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersFromSuggestion', array());

        return parent::getUsersFromSuggestion();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersToSuggestion(\Eplugg\BackBundle\Entity\Suggestion $usersToSuggestion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersToSuggestion', array($usersToSuggestion));

        return parent::addUsersToSuggestion($usersToSuggestion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersToSuggestion(\Eplugg\BackBundle\Entity\Suggestion $usersToSuggestion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersToSuggestion', array($usersToSuggestion));

        return parent::removeUsersToSuggestion($usersToSuggestion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersToSuggestion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersToSuggestion', array());

        return parent::getUsersToSuggestion();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersSuggested(\Eplugg\BackBundle\Entity\Suggestion $usersSuggested)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersSuggested', array($usersSuggested));

        return parent::addUsersSuggested($usersSuggested);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersSuggested(\Eplugg\BackBundle\Entity\Suggestion $usersSuggested)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersSuggested', array($usersSuggested));

        return parent::removeUsersSuggested($usersSuggested);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersSuggested()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersSuggested', array());

        return parent::getUsersSuggested();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserFromIgnoredId(\Eplugg\BackBundle\Entity\Ignored $userFromIgnoredId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserFromIgnoredId', array($userFromIgnoredId));

        return parent::addUserFromIgnoredId($userFromIgnoredId);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserFromIgnoredId(\Eplugg\BackBundle\Entity\Ignored $userFromIgnoredId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserFromIgnoredId', array($userFromIgnoredId));

        return parent::removeUserFromIgnoredId($userFromIgnoredId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserFromIgnoredId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserFromIgnoredId', array());

        return parent::getUserFromIgnoredId();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserIgnoredId(\Eplugg\BackBundle\Entity\Ignored $userIgnoredId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserIgnoredId', array($userIgnoredId));

        return parent::addUserIgnoredId($userIgnoredId);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserIgnoredId(\Eplugg\BackBundle\Entity\Ignored $userIgnoredId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserIgnoredId', array($userIgnoredId));

        return parent::removeUserIgnoredId($userIgnoredId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserIgnoredId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserIgnoredId', array());

        return parent::getUserIgnoredId();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserEvent(\Eplugg\BackBundle\Entity\EventCalendar $userEvents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserEvent', array($userEvents));

        return parent::addUserEvent($userEvents);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserEvent(\Eplugg\BackBundle\Entity\EventCalendar $userEvents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserEvent', array($userEvents));

        return parent::removeUserEvent($userEvents);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserEvents', array());

        return parent::getUserEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function addActivity(\Eplugg\BackBundle\Entity\Activity $activities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActivity', array($activities));

        return parent::addActivity($activities);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActivity(\Eplugg\BackBundle\Entity\Activity $activities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActivity', array($activities));

        return parent::removeActivity($activities);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAllActivities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAllActivities', array());

        return parent::removeAllActivities();
    }

    /**
     * {@inheritDoc}
     */
    public function getActivities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivities', array());

        return parent::getActivities();
    }

    /**
     * {@inheritDoc}
     */
    public function getActivitiesFormatted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivitiesFormatted', array());

        return parent::getActivitiesFormatted();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserLog(\Eplugg\BackBundle\Entity\ProfileLog $userLog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserLog', array($userLog));

        return parent::addUserLog($userLog);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserLog(\Eplugg\BackBundle\Entity\ProfileLog $userLog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserLog', array($userLog));

        return parent::removeUserLog($userLog);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserLog()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserLog', array());

        return parent::getUserLog();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserLogTarget(\Eplugg\BackBundle\Entity\ProfileLog $userLogTarget)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserLogTarget', array($userLogTarget));

        return parent::addUserLogTarget($userLogTarget);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserLogTarget(\Eplugg\BackBundle\Entity\ProfileLog $userLogTarget)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserLogTarget', array($userLogTarget));

        return parent::removeUserLogTarget($userLogTarget);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserLogTarget()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserLogTarget', array());

        return parent::getUserLogTarget();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimer($timer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimer', array($timer));

        return parent::setTimer($timer);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimer', array());

        return parent::getTimer();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', array($latitude));

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', array());

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', array($longitude));

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', array());

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', array($role));

        return parent::addRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsernameCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsernameCanonical', array());

        return parent::getUsernameCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCanonical', array());

        return parent::getEmailCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainPassword', array());

        return parent::getPlainPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', array());

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationToken', array());

        return parent::getConfirmationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function hasRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRole', array($role));

        return parent::hasRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', array());

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', array());

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', array());

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsExpired', array());

        return parent::isCredentialsExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function isExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExpired', array());

        return parent::isExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLocked', array());

        return parent::isLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isSuperAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSuperAdmin', array());

        return parent::isSuperAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', array($role));

        return parent::removeRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsernameCanonical($usernameCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsernameCanonical', array($usernameCanonical));

        return parent::setUsernameCanonical($usernameCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpireAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpireAt', array($date));

        return parent::setCredentialsExpireAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpired', array($boolean));

        return parent::setCredentialsExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCanonical($emailCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCanonical', array($emailCanonical));

        return parent::setEmailCanonical($emailCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', array($boolean));

        return parent::setEnabled($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpired', array($boolean));

        return parent::setExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiresAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiresAt', array($date));

        return parent::setExpiresAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperAdmin($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperAdmin', array($boolean));

        return parent::setSuperAdmin($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainPassword', array($password));

        return parent::setPlainPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin(\DateTime $time = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', array($time));

        return parent::setLastLogin($time);
    }

    /**
     * {@inheritDoc}
     */
    public function setLocked($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocked', array($boolean));

        return parent::setLocked($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationToken($confirmationToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationToken', array($confirmationToken));

        return parent::setConfirmationToken($confirmationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordRequestedAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordRequestedAt', array($date));

        return parent::setPasswordRequestedAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordRequestedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordRequestedAt', array());

        return parent::getPasswordRequestedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isPasswordRequestNonExpired($ttl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPasswordRequestNonExpired', array($ttl));

        return parent::isPasswordRequestNonExpired($ttl);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', array($roles));

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', array());

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupNames', array());

        return parent::getGroupNames();
    }

    /**
     * {@inheritDoc}
     */
    public function hasGroup($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasGroup', array($name));

        return parent::hasGroup($name);
    }

    /**
     * {@inheritDoc}
     */
    public function addGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGroup', array($group));

        return parent::addGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGroup', array($group));

        return parent::removeGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
