<?php
error_reporting(0);
//	file_put_contents('/tmp/aa',var_export($_POST,true));
	header('Content-type: application/json');
	define("GOOGLE_API_KEY", "AIzaSyDX4xmm5qVtWSjMU93R3EK-8vO-KdCs_Dg");
	$con=mysql_connect("localhost","eplugg2_user","Pm25#M2etQ");
	mysql_select_db("eplugg");
	mysql_query('SET CHARACTER SET utf8;');
	ini_set('default_charset','utf-8');
	$json_session="session";
	$json_user_type="user_type";
	$json_id="id";
	$json_sex="sex";
	$json_firstname="firstname";
	$json_lastname="lastname";
	$json_job="job";
	$json_picture="picture";
	$json_emails="emails";
	$json_mobiles="mobiles";
	$json_fixs="fixs";
	$json_establishment_name="establishment_name";
	$json_establishment_activities="establishment_activities";
	$json_establishment_country="establishment_country";
	$json_establishment_city="establishment_city";
	$json_establishment_picture="establishment_picture";
	$json_establishment_address="establishment_address";
	$json_establishment_fixs="establishment_fixs";
	$json_establishment_faxs="establishment_faxs";
	$json_establishment_web_sites="establishment_web_sites";
	$json_common_friends="common_friends";
	$json_status="status";
	$json_name="name";
	$json_to_user_id="to_user_id";
	$json_from_user_id="from_user_id";
	$json_timestamp="timestamp";
	$json_invitation_count="invitation_count";
	$path_picture="http://192.168.1.5:8888/static/user_up/";
	$user_type_without_mail_confirmation=0;
	$user_type_with_step2=2;
?>
