<?php
namespace Core\Config;

define('DB_HOST'    ,'localhost');
define('DB_PORT'    ,'3306');
define('DB_NAME'    ,'prj_eplugg');
define('DB_USER'    ,'prj_eplugg');
define('DB_PASSWD'  ,'ZVVbCBeNdMJK');

define('S'          , DIRECTORY_SEPARATOR );
define('BASE'       , realpath(dirname(__FILE__).S));
define('DIR'        , __DIR__.S);
define('LIB_DIR'    , DIR.'lib'.S);
define('LANG_DIR'   , DIR.'lang'.S);
define('TPL_DIR'    , DIR.'tpl'.S);
define('API_DIR'    , DIR.'api'.S);
define('CONTROLLER_DIR'    , DIR.'controller'.S);
define('CORE_DIR'    , DIR . 'core' . S);
define('USER_PICS_DIR'    , DIR.'..'.S.'www'.S.'static'.S);

define('DOMAIN', 'http://eplugg.local');
define('STATIC_DIR'    , DOMAIN . '/static');
define('USERUP_DIR'    , DOMAIN . '/static/user_up/');
define('AJAX_REQUEST', strtolower(getenv('HTTP_X_REQUESTED_WITH')) === 'xmlhttprequest');

define('ACCESS_PRIVATE',0);
define('ACCESS_PUBLIC',1);
define('ACCESS_DEFAULT',ACCESS_PRIVATE);
define('AJAX_OUTPUT_ONLY',1);
define('HTML_OUTPUT_ONLY',2);

define('GOLD_USER',2);
class Vars{
	static public $GET_routes = array(
		'testTw'                	=> array('Index','testTw',ACCESS_PUBLIC,HTML_OUTPUT_ONLY),	
		
		''                	  		=> array('Index','main',ACCESS_PUBLIC,HTML_OUTPUT_ONLY),		
		'lang' 			  	  		=> array('Index','change_language',ACCESS_PUBLIC),
		'eplugg'  					=> array('Index','search',ACCESS_PUBLIC,HTML_OUTPUT_ONLY),
		'profile'  					=> array('Index','profile',ACCESS_PUBLIC,HTML_OUTPUT_ONLY),
		'legal_informations'  		=> array('Index','legal_informations',ACCESS_PUBLIC,HTML_OUTPUT_ONLY),
		'about'  					=> array('Index','about',ACCESS_PUBLIC,HTML_OUTPUT_ONLY),
		'terms'  					=> array('Index','terms',ACCESS_PUBLIC,HTML_OUTPUT_ONLY),
		
		'is_logged_in'	      		=> array('Auth','is_logged_in',ACCESS_PUBLIC),
		'login'           	  		=> array('Auth','login',ACCESS_PUBLIC),
		'login/password'           	=> array('Auth','password',ACCESS_PUBLIC),		
		'logout'          	  		=> array('Auth','logout',ACCESS_PRIVATE),
		
		'members.json'  			=> array('User','get_members_list',ACCESS_PUBLIC,AJAX_OUTPUT_ONLY),
		'signup'	          		=> array('User','signup_essentials_submit',ACCESS_PUBLIC),
		'signup_step2'	      		=> array('User','signup_extended_show',ACCESS_PRIVATE),
		'get_count_messages'		=> array('User','getUnreadMessagesCount',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),	
		
		'user'  					=> array('Profile','index',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'edit_profile'  			=> array('Profile','edit',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'edit_image'  				=> array('Profile','editImage',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'delete_image' 				=> array('Profile','deleteImage',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'edit_logo'  				=> array('Profile','editLogo',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'delete_logo' 				=> array('Profile','deleteLogo',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),		
		'add_cv'  					=> array('Profile','addCv',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'edit_cv'  					=> array('Profile','editCv',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),	
		'upload_cv'  				=> array('Profile','uploadCv',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'delete_cv_file'			=> array('Profile','deleteCvFile',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'delete_cv'  				=> array('Profile','deleteCv',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),	
		'setting'  					=> array('Profile','setting',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),	
		'success'  					=> array('Profile','success',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),	
		'mutual_friend'				=> array('Profile','mutualFriend',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),	
		
		
		'invitations'  				=> array('Invitation','index',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),		
		
		'suggest'    	  	  		=> array('Suggestion','index',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		
		'messages'  				=> array('Message','index',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'contacts_messages'  		=> array('Message','contacts',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		
		'directory'  				=> array('Directory','index',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'activity'  				=> array('Directory','activity',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'directory_search'  		=> array('Directory','search',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'ct_search'  				=> array('Directory','ctSearch',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),	
		
		
		'search'  					=> array('Search','index',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'advanced_search'  			=> array('Search','advanced',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		
		
		
		
		
	    'index'          			=> array('Index','main',ACCESS_PUBLIC),
	    'vc'           	  	  		=> array('VisitCard','get_mini',ACCESS_PUBLIC,AJAX_OUTPUT_ONLY),
	    
	    'hash'          	  		=> array('Crypt','hash'),
	    'do_login'  	      		=> array('Login','do_login'),	    
	    'upload_user_picture' 		=> array('User','upload_user_picture',ACCESS_PRIVATE),
	    
    	'test' 			  	  		=> array('Index','test',ACCESS_PUBLIC,AJAX_OUTPUT_ONLY),	    
	    'signup_step2_ignore' 		=> array('User','signup_extended_ignore',ACCESS_PRIVATE),
	    'getinfo.json' 	  	  		=> array('VisitCard','get_mini',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	    'getcommuncontacts.json'	=> array('User','get_common_contacts',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	    'sendvc'  					=> array('Index','test',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	    'deleteVC'  				=> array('VisitCard','deletevc',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	    'getcontactslist.json'  	=> array('User','get_friends_list',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),	    
	    
	    
	    'agenda'  					=> array('Agenda','index',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
	    'getevents'  				=> array('Agenda','getevents',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	    'poll'  					=> array('Index','poll',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
	    'dir_seen'  				=> array('Index','dir_seen',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	    'msg_seen'  				=> array('Index','msg_seen',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	    'notif_seen'  				=> array('Index','notif_seen',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	    'share'  					=> array('Index','share',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),	    
	    'userstatus'  				=> array('Index','userstatus',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
	    'dc'  						=> array('Index','dialcode',ACCESS_PUBLIC,HTML_OUTPUT_ONLY),
	    
		'postit'  					=> array('Postit','index',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	);

	static public $POST_routes = array(	
		'eplugg'  					=> array('Index','search',ACCESS_PUBLIC,HTML_OUTPUT_ONLY),
		
		'login'              	 	=> array('Auth','login',ACCESS_PUBLIC),
		'login/password'           	=> array('Auth','password',ACCESS_PUBLIC),
		
		'signup'              		=> array('User','signup_essentials_submit',ACCESS_PUBLIC),
		'signup_step2'    	  		=> array('User','signup_extended_submit',ACCESS_PRIVATE),
		'user_search'  				=> array('User','search',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),			
		
		'save_profile'				=> array('Profile','saveProfile',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'upload_image' 				=> array('Profile','uploadImage',ACCESS_PRIVATE),
	    'save_image'				=> array('Profile','saveImage',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),		
		'upload_logo' 				=> array('Profile','uploadLogo',ACCESS_PRIVATE),
		'save_logo'					=> array('Profile','saveLogo',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'delete_contact'  			=> array('Profile','delete',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),			
		'save_cv'  					=> array('Profile','saveCv',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'upload_cv'  				=> array('Profile','uploadCv',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'delete_cv_file'			=> array('Profile','deleteCvFile',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'delete_image' 				=> array('Profile','deleteImage',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'delete_logo' 				=> array('Profile','deleteLogo',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		'setting'  					=> array('Profile','setting',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		
		'plugger'					=> array('Invitation','plugger',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
		'vplugger'					=> array('Invitation','vplugger',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
		'iplugger'					=> array('Invitation','iplugger',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
		
		'suggest'    	  	  		=> array('Suggestion','index',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		
		'messages'  				=> array('Message','index',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),	
		'msg_search'  				=> array('Message','search',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),	
		
		'search'  					=> array('Search','index',ACCESS_PRIVATE,HTML_OUTPUT_ONLY),
		
		
		
	    'upload_user_picture' 		=> array('User','upload_user_picture',ACCESS_PRIVATE),
	    'upload_company_logo' 		=> array('User','upload_company_logo',ACCESS_PRIVATE),	 
	    'sendmsg'    	  	 		=> array('Message','send',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	    'sendmsg_inbox'    	  		=> array('Message','send_inbox',ACCESS_PRIVATE),
	   	
	   	'search_top'  				=> array('Search','search_top',ACCESS_PRIVATE),
	   	'update_cv_pro'  			=> array('Profile','update_cv_pro',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	   	'update_cv_acad'  			=> array('Profile','update_cv_academic',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	   	'addevent'  				=> array('Agenda','addevent',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	   	'postit'  					=> array('Postit','index',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),	   	
	   	'edit_profile_submit'		=> array('Profile','edit_submit',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	   	'chat'						=> array('Message','chat',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	   	'getcontactslist.json'		=> array('Users','get_all_friends_list',ACCESS_PRIVATE,AJAX_OUTPUT_ONLY),
	);
	
	public static $languages = array(
		'en' => true,
		'fr' => true,
	);

	public static $user_lang = 'en';
	public static $countries = array(
		'AF' => 'Afghanistan',
		'AX' => 'Åland Islands',
		'AL' => 'Albania',
		'DZ' => 'Algeria',
		'AS' => 'American Samoa',
		'AD' => 'Andorra',
		'AO' => 'Angola',
		'AI' => 'Anguilla',
		'AQ' => 'Antarctica',
		'AG' => 'Antigua and Barbuda',
		'AR' => 'Argentina',
		'AM' => 'Armenia',
		'AW' => 'Aruba',
		'AU' => 'Australia',
		'AT' => 'Austria',
		'AZ' => 'Azerbaijan',
		'BS' => 'Bahamas',
		'BH' => 'Bahrain',
		'BD' => 'Bangladesh',
		'BB' => 'Barbados',
		'BY' => 'Belarus',
		'BE' => 'Belgium',
		'BZ' => 'Belize',
		'BJ' => 'Benin',
		'BM' => 'Bermuda',
		'BT' => 'Bhutan',
		'BO' => 'Bolivia, Plurinational State of',
		'BQ' => 'Bonaire, Sint Eustatius and Saba',
		'BA' => 'Bosnia and Herzegovina',
		'BW' => 'Botswana',
		'BV' => 'Bouvet Island',
		'BR' => 'Brazil',
		'IO' => 'British Indian Ocean Territory',
		'BN' => 'Brunei Darussalam',
		'BG' => 'Bulgaria',
		'BF' => 'Burkina Faso',
		'BI' => 'Burundi',
		'KH' => 'Cambodia',
		'CM' => 'Cameroon',
		'CA' => 'Canada',
		'CV' => 'Cape Verde',
		'KY' => 'Cayman Islands',
		'CF' => 'Central African Republic',
		'TD' => 'Chad',
		'CL' => 'Chile',
		'CN' => 'China',
		'CX' => 'Christmas Island',
		'CC' => 'Cocos (Keeling) Islands',
		'CO' => 'Colombia',
		'KM' => 'Comoros',
		'CG' => 'Congo',
		'CD' => 'Congo, the Democratic Republic of the',
		'CK' => 'Cook Islands',
		'CR' => 'Costa Rica',
		'CI' => 'Ivory Coast',
		'HR' => 'Croatia',
		'CU' => 'Cuba',
		'CW' => 'Curaçao',
		'CY' => 'Cyprus',
		'CZ' => 'Czech Republic',
		'DK' => 'Denmark',
		'DJ' => 'Djibouti',
		'DM' => 'Dominica',
		'DO' => 'Dominican Republic',
		'EC' => 'Ecuador',
		'EG' => 'Egypt',
		'SV' => 'El Salvador',
		'GQ' => 'Equatorial Guinea',
		'ER' => 'Eritrea',
		'EE' => 'Estonia',
		'ET' => 'Ethiopia',
		'FK' => 'Falkland Islands (Malvinas)',
		'FO' => 'Faroe Islands',
		'FJ' => 'Fiji',
		'FI' => 'Finland',
		'FR' => 'France',
		'GF' => 'French Guiana',
		'PF' => 'French Polynesia',
		'TF' => 'French Southern Territories',
		'GA' => 'Gabon',
		'GM' => 'Gambia',
		'GE' => 'Georgia',
		'DE' => 'Germany',
		'GH' => 'Ghana',
		'GI' => 'Gibraltar',
		'GR' => 'Greece',
		'GL' => 'Greenland',
		'GD' => 'Grenada',
		'GP' => 'Guadeloupe',
		'GU' => 'Guam',
		'GT' => 'Guatemala',
		'GG' => 'Guernsey',
		'GN' => 'Guinea',
		'GW' => 'Guinea-Bissau',
		'GY' => 'Guyana',
		'HT' => 'Haiti',
		'HM' => 'Heard Island and McDonald Islands',
		'VA' => 'Holy See (Vatican City State)',
		'HN' => 'Honduras',
		'HK' => 'Hong Kong',
		'HU' => 'Hungary',
		'IS' => 'Iceland',
		'IN' => 'India',
		'ID' => 'Indonesia',
		'IR' => 'Iran, Islamic Republic of',
		'IQ' => 'Iraq',
		'IE' => 'Ireland',
		'IM' => 'Isle of Man',
		'IL' => 'Israel',
		'IT' => 'Italy',
		'JM' => 'Jamaica',
		'JP' => 'Japan',
		'JE' => 'Jersey',
		'JO' => 'Jordan',
		'KZ' => 'Kazakhstan',
		'KE' => 'Kenya',
		'KI' => 'Kiribati',
		'KP' => 'Korea, Democratic People\'s Republic of',
		'KR' => 'Korea, Republic of',
		'KW' => 'Kuwait',
		'KG' => 'Kyrgyzstan',
		'LA' => 'Lao People\'s Democratic Republic',
		'LV' => 'Latvia',
		'LB' => 'Lebanon',
		'LS' => 'Lesotho',
		'LR' => 'Liberia',
		'LY' => 'Libya',
		'LI' => 'Liechtenstein',
		'LT' => 'Lithuania',
		'LU' => 'Luxembourg',
		'MO' => 'Macao',
		'MK' => 'Macedonia, the former Yugoslav Republic of',
		'MG' => 'Madagascar',
		'MW' => 'Malawi',
		'MY' => 'Malaysia',
		'MV' => 'Maldives',
		'ML' => 'Mali',
		'MT' => 'Malta',
		'MH' => 'Marshall Islands',
		'MQ' => 'Martinique',
		'MR' => 'Mauritania',
		'MU' => 'Mauritius',
		'YT' => 'Mayotte',
		'MX' => 'Mexico',
		'FM' => 'Micronesia, Federated States of',
		'MD' => 'Moldova, Republic of',
		'MC' => 'Monaco',
		'MN' => 'Mongolia',
		'ME' => 'Montenegro',
		'MS' => 'Montserrat',
		'MA' => 'Morocco',
		'MZ' => 'Mozambique',
		'MM' => 'Myanmar',
		'NA' => 'Namibia',
		'NR' => 'Nauru',
		'NP' => 'Nepal',
		'NL' => 'Netherlands',
		'NC' => 'New Caledonia',
		'NZ' => 'New Zealand',
		'NI' => 'Nicaragua',
		'NE' => 'Niger',
		'NG' => 'Nigeria',
		'NU' => 'Niue',
		'NF' => 'Norfolk Island',
		'MP' => 'Northern Mariana Islands',
		'NO' => 'Norway',
		'OM' => 'Oman',
		'PK' => 'Pakistan',
		'PW' => 'Palau',
		'PS' => 'Palestinian Territory, Occupied',
		'PA' => 'Panama',
		'PG' => 'Papua New Guinea',
		'PY' => 'Paraguay',
		'PE' => 'Peru',
		'PH' => 'Philippines',
		'PN' => 'Pitcairn',
		'PL' => 'Poland',
		'PT' => 'Portugal',
		'PR' => 'Puerto Rico',
		'QA' => 'Qatar',
		'RE' => 'Réunion',
		'RO' => 'Romania',
		'RU' => 'Russian Federation',
		'RW' => 'Rwanda',
		'BL' => 'Saint Barthélemy',
		'SH' => 'Saint Helena, Ascension and Tristan da Cunha',
		'KN' => 'Saint Kitts and Nevis',
		'LC' => 'Saint Lucia',
		'MF' => 'Saint Martin (French part)',
		'PM' => 'Saint Pierre and Miquelon',
		'VC' => 'Saint Vincent and the Grenadines',
		'WS' => 'Samoa',
		'SM' => 'San Marino',
		'ST' => 'Sao Tome and Principe',
		'SA' => 'Saudi Arabia',
		'SN' => 'Senegal',
		'RS' => 'Serbia',
		'SC' => 'Seychelles',
		'SL' => 'Sierra Leone',
		'SG' => 'Singapore',
		'SX' => 'Sint Maarten (Dutch part)',
		'SK' => 'Slovakia',
		'SI' => 'Slovenia',
		'SB' => 'Solomon Islands',
		'SO' => 'Somalia',
		'ZA' => 'South Africa',
		'GS' => 'South Georgia and the South Sandwich Islands',
		'SS' => 'South Sudan',
		'ES' => 'Spain',
		'LK' => 'Sri Lanka',
		'SD' => 'Sudan',
		'SR' => 'Suriname',
		'SJ' => 'Svalbard and Jan Mayen',
		'SZ' => 'Swaziland',
		'SE' => 'Sweden',
		'CH' => 'Switzerland',
		'SY' => 'Syrian Arab Republic',
		'TW' => 'Taiwan, Province of China',
		'TJ' => 'Tajikistan',
		'TZ' => 'Tanzania, United Republic of',
		'TH' => 'Thailand',
		'TL' => 'Timor-Leste',
		'TG' => 'Togo',
		'TK' => 'Tokelau',
		'TO' => 'Tonga',
		'TT' => 'Trinidad and Tobago',
		'TN' => 'Tunisia',
		'TR' => 'Turkey',
		'TM' => 'Turkmenistan',
		'TC' => 'Turks and Caicos Islands',
		'TV' => 'Tuvalu',
		'UG' => 'Uganda',
		'UK' => 'Ukraine',
		'AE' => 'United Arab Emirates',
		'GB' => 'United Kingdom',
		'US' => 'United States',
		'UM' => 'United States Minor Outlying Islands',
		'UY' => 'Uruguay',
		'UZ' => 'Uzbekistan',
		'VU' => 'Vanuatu',
		'VE' => 'Venezuela, Bolivarian Republic of',
		'VN' => 'Viet Nam',
		'VG' => 'Virgin Islands, British',
		'VI' => 'Virgin Islands, U.S.',
		'WF' => 'Wallis and Futuna',
		'EH' => 'Western Sahara',
		'YE' => 'Yemen',
		'ZM' => 'Zambia',
		'ZW' => 'Zimbabwe',
	);
		
	public static $dial_codes = array(
		'AD'=>'376',
		'AE'=>'971',
		'AF'=>'93',
		'AG'=>'1268',
		'AI'=>'1264',
		'AL'=>'355',
		'AM'=>'374',
		'AN'=>'599',
		'AO'=>'244',
		'AQ'=>'672',
		'AR'=>'54',
		'AS'=>'1684',
		'AT'=>'43',
		'AU'=>'61',
		'AW'=>'297',
		'AZ'=>'994',
		'BA'=>'387',
		'BB'=>'1246',
		'BD'=>'880',
		'BE'=>'32',
		'BF'=>'226',
		'BG'=>'359',
		'BH'=>'973',
		'BI'=>'257',
		'BJ'=>'229',
		'BL'=>'590',
		'BM'=>'1441',
		'BN'=>'673',
		'BO'=>'591',
		'BR'=>'55',
		'BS'=>'1242',
		'BT'=>'975',
		'BW'=>'267',
		'BY'=>'375',
		'BZ'=>'501',
		'CA'=>'1',
		'CC'=>'61',
		'CD'=>'243',
		'CF'=>'236',
		'CG'=>'242',
		'CH'=>'41',
		'CI'=>'225',
		'CK'=>'682',
		'CL'=>'56',
		'CM'=>'237',
		'CN'=>'86',
		'CO'=>'57',
		'CR'=>'506',
		'CU'=>'53',
		'CV'=>'238',
		'CX'=>'61',
		'CY'=>'357',
		'CZ'=>'420',
		'DE'=>'49',
		'DJ'=>'253',
		'DK'=>'45',
		'DM'=>'1767',
		'DO'=>'1809',
		'DZ'=>'213',
		'EC'=>'593',
		'EE'=>'372',
		'EG'=>'20',
		'ER'=>'291',
		'ES'=>'34',
		'ET'=>'251',
		'FI'=>'358',
		'FJ'=>'679',
		'FK'=>'500',
		'FM'=>'691',
		'FO'=>'298',
		'FR'=>'33',
		'GA'=>'241',
		'GB'=>'44',
		'GD'=>'1473',
		'GE'=>'995',
		'GH'=>'233',
		'GI'=>'350',
		'GL'=>'299',
		'GM'=>'220',
		'GN'=>'224',
		'GQ'=>'240',
		'GR'=>'30',
		'GT'=>'502',
		'GU'=>'1671',
		'GW'=>'245',
		'GY'=>'592',
		'HK'=>'852',
		'HN'=>'504',
		'HR'=>'385',
		'HT'=>'509',
		'HU'=>'36',
		'ID'=>'62',
		'IE'=>'353',
		'IL'=>'972',
		'IM'=>'44',
		'IN'=>'91',
		'IQ'=>'964',
		'IR'=>'98',
		'IS'=>'354',
		'IT'=>'39',
		'JM'=>'1876',
		'JO'=>'962',
		'JP'=>'81',
		'KE'=>'254',
		'KG'=>'996',
		'KH'=>'855',
		'KI'=>'686',
		'KM'=>'269',
		'KN'=>'1869',
		'KP'=>'850',
		'KR'=>'82',
		'KW'=>'965',
		'KY'=>'1345',
		'KZ'=>'7',
		'LA'=>'856',
		'LB'=>'961',
		'LC'=>'1758',
		'LI'=>'423',
		'LK'=>'94',
		'LR'=>'231',
		'LS'=>'266',
		'LT'=>'370',
		'LU'=>'352',
		'LV'=>'371',
		'LY'=>'218',
		'MA'=>'212',
		'MC'=>'377',
		'MD'=>'373',
		'ME'=>'382',
		'MF'=>'1599',
		'MG'=>'261',
		'MH'=>'692',
		'MK'=>'389',
		'ML'=>'223',
		'MM'=>'95',
		'MN'=>'976',
		'MO'=>'853',
		'MP'=>'1670',
		'MR'=>'222',
		'MS'=>'1664',
		'MT'=>'356',
		'MU'=>'230',
		'MV'=>'960',
		'MW'=>'265',
		'MX'=>'52',
		'MY'=>'60',
		'MZ'=>'258',
		'NA'=>'264',
		'NC'=>'687',
		'NE'=>'227',
		'NG'=>'234',
		'NI'=>'505',
		'NL'=>'31',
		'NO'=>'47',
		'NP'=>'977',
		'NR'=>'674',
		'NU'=>'683',
		'NZ'=>'64',
		'OM'=>'968',
		'PA'=>'507',
		'PE'=>'51',
		'PF'=>'689',
		'PG'=>'675',
		'PH'=>'63',
		'PK'=>'92',
		'PL'=>'48',
		'PM'=>'508',
		'PN'=>'870',
		'PR'=>'1',
		'PT'=>'351',
		'PW'=>'680',
		'PY'=>'595',
		'QA'=>'974',
		'RO'=>'40',
		'RS'=>'381',
		'RU'=>'7',
		'RW'=>'250',
		'SA'=>'966',
		'SB'=>'677',
		'SC'=>'248',
		'SD'=>'249',
		'SE'=>'46',
		'SG'=>'65',
		'SH'=>'290',
		'SI'=>'386',
		'SK'=>'421',
		'SL'=>'232',
		'SM'=>'378',
		'SN'=>'221',
		'SO'=>'252',
		'SR'=>'597',
		'ST'=>'239',
		'SV'=>'503',
		'SY'=>'963',
		'SZ'=>'268',
		'TC'=>'1649',
		'TD'=>'235',
		'TG'=>'228',
		'TH'=>'66',
		'TJ'=>'992',
		'TK'=>'690',
		'TL'=>'670',
		'TM'=>'993',
		'TN'=>'216',
		'TO'=>'676',
		'TR'=>'90',
		'TT'=>'1868',
		'TV'=>'688',
		'TW'=>'886',
		'TZ'=>'255',
		'UK'=>'380',
		'UG'=>'256',
		'US'=>'1',
		'UY'=>'598',
		'UZ'=>'998',
		'VA'=>'39',
		'VC'=>'1784',
		'VE'=>'58',
		'VG'=>'1284',
		'VI'=>'1340',
		'VN'=>'84',
		'VU'=>'678',
		'WF'=>'681',
		'WS'=>'685',
		'YE'=>'967',
		'YT'=>'262',
		'ZA'=>'27',
		'ZM'=>'260',
		'ZW'=>'263'
	);
	public static function dispatch($route, $argv){
		$action = null;
		switch($route){
			case 'login':
				$action = "\\Controller\\Login";
		}
		return $action;
	}
	public static function getCountry($c){
		$uc = array_search($c,self::$countries);
		if($uc === false) $uc = 'US';
		return \Lang\Aux::$countries[$uc];
	}
}
//date_default_timezone_set('UTC');
mb_internal_encoding("UTF-8");
